@tool
extends EditorExportPlugin
## Wires an iOS build to the same `mobile_services.cfg` the Android one reads.
##
## LESS WORK THAN THE ANDROID SIDE, because Godot's iOS plugin format (`.gdip`)
## already declares each native plugin's frameworks, static libraries and linker
## flags, and the export preset already lets you switch them on per build. What
## `.gdip` cannot do is read a config file — so what is left for this class is
## everything whose value comes from the game rather than from the plugin:
##
## - `GADApplicationIdentifier`, without which AdMob's initialiser throws on
##   launch, exactly as on Android;
## - `AppLovinSdkKey`, for a MAX build;
## - `NSUserTrackingUsageDescription`, without which the ATT prompt cannot be
##   shown at all and Apple rejects the build for asking;
## - `SKAdNetworkItems`, the ad networks allowed to receive install attribution;
## - `GoogleService-Info.plist`, bundled from wherever the project keeps it.
##
## THE NATIVE HALVES ARE NOT BUILT HERE. Godot iOS plugins are static libraries
## that need macOS and Xcode; `tools/build_ios.sh` builds them on a Mac and this
## plugin only checks that the result was installed. See docs/ios.md — including
## what is and is not verified, which on iOS is a shorter list than on Android.

const Editor := preload("res://addons/mobile_services/editor/editor_config.gd")

## Where Godot looks for iOS plugin descriptors in a project.
const PLUGIN_DIR := "res://ios/plugins"

## One `.gdip` per native module, same names as the Android AARs.
const MODULE_PLUGINS := {
	"core": "mobile_services_core.gdip",
	"firebase": "mobile_services_firebase.gdip",
	"ads": "mobile_services_ads.gdip",
	"billing": "mobile_services_billing.gdip",
	"playgames": "mobile_services_gamecenter.gdip",
	"consent": "mobile_services_consent.gdip",
}

## Where a project keeps Firebase's iOS configuration. Checked in this order;
## the first one found is bundled.
const FIREBASE_PLIST_PATHS := [
	"res://ios/GoogleService-Info.plist",
	"res://GoogleService-Info.plist",
]

## A project can list the ad networks it works with, one identifier per line,
## and this file is used instead of [constant DEFAULT_SKADNETWORK_IDS].
##
## WHY IT IS A FILE AND NOT A CONSTANT. The list changes whenever a mediated
## network is added or drops out, it runs to a hundred entries for a full MAX
## waterfall, and both Google and AppLovin publish the current one. Baking a
## snapshot into an addon guarantees it is out of date; reading a file the game
## owns means updating it is a one-line commit in that game.
const SKADNETWORK_FILE := "res://skadnetwork_ids.txt"

## Enough to attribute installs to Google's own network. Anything mediated needs
## the full list — see docs/ios.md.
const DEFAULT_SKADNETWORK_IDS := ["cstr6suwn9.skadnetwork"]

var _config: MSConfig = null
var _modules: PackedStringArray = PackedStringArray()


func _get_name() -> String:
	return "MobileServicesIOS"


func _supports_platform(platform: EditorExportPlatform) -> bool:
	return platform is EditorExportPlatformIOS


func _export_begin(
	features: PackedStringArray, debug: bool, _path: String, _flags: int
) -> void:
	if not features.has("ios"):
		return
	_config = Editor.load_for_export(debug)
	_modules = Editor.required_modules(_config)

	var blocking := Editor.blocking_problems(_config, "ios", debug)
	if not blocking.is_empty():
		push_error("[MobileServices] EXPORT WILL BE BROKEN — %s" % blocking)
	for warning in _config.warnings:
		push_warning("[MobileServices] %s" % warning)

	_check_plugins_installed()
	add_ios_plist_content(_plist_content())
	_bundle_firebase_plist()
	print("[MobileServices] iOS build %s: modules %s" % [Editor.VERSION, ", ".join(_modules)])
	print(_podfile_advice())


func _export_end() -> void:
	_config = null
	_modules = PackedStringArray()


## Names a module whose `.gdip` is not in the project.
##
## A missing descriptor is not an error Godot reports: the plugin simply is not
## there, `Engine.has_singleton` answers false, and every call to that service
## returns SERVICE_UNAVAILABLE for the life of the build. Which looks exactly
## like a game whose players do not buy anything.
func _check_plugins_installed() -> void:
	for module in _modules:
		var descriptor: String = PLUGIN_DIR.path_join(MODULE_PLUGINS.get(module, ""))
		if not FileAccess.file_exists(descriptor):
			push_error(
				"[MobileServices] %s is enabled but %s is not in this project. " % [
					module, descriptor
				]
				+ "Build the iOS plugins on a Mac (addons/mobile_services/tools/"
				+ "build_ios.sh) and copy addons/mobile_services/ios/plugins/ into "
				+ "res://ios/plugins/. Also switch the plugin on in the export preset."
			)


## The Info.plist keys whose values come from `mobile_services.cfg`.
func _plist_content() -> String:
	var lines := PackedStringArray([
		"<!-- Generated by the mobile_services addon. -->",
	])
	if _modules.has("ads"):
		lines.append("<key>GADApplicationIdentifier</key>")
		lines.append("<string>%s</string>" % _escape(_config.get_ads_app_id("ios")))
		if str(_config.ads["provider"]) == "applovin_max":
			lines.append("<key>AppLovinSdkKey</key>")
			lines.append("<string>%s</string>" % _escape(str(_config.ads["applovin_sdk_key"])))
		lines.append("<key>SKAdNetworkItems</key>")
		lines.append("<array>")
		for identifier in _skadnetwork_ids():
			lines.append("\t<dict>")
			lines.append("\t\t<key>SKAdNetworkIdentifier</key>")
			lines.append("\t\t<string>%s</string>" % _escape(identifier))
			lines.append("\t</dict>")
		lines.append("</array>")
	if _modules.has("consent") and bool(_config.consent["att_prompt"]):
		lines.append("<key>NSUserTrackingUsageDescription</key>")
		lines.append("<string>%s</string>" % _escape(str(_config.consent["att_message"])))
	if _modules.has("firebase"):
		# Firebase's iOS SDK collects the IDFA through its ad-support component
		# unless told otherwise; the SDK reads this before the app runs, so it
		# cannot be set from GDScript. Same reasoning as the Android manifest.
		lines.append("<key>GOOGLE_ANALYTICS_DEFAULT_ALLOW_AD_PERSONALIZATION_SIGNALS</key>")
		lines.append("<false/>")
		lines.append("<key>FIREBASE_ANALYTICS_COLLECTION_DEACTIVATED</key>")
		lines.append("<false/>")
	return "\n".join(lines)


func _skadnetwork_ids() -> PackedStringArray:
	var identifiers := PackedStringArray()
	if FileAccess.file_exists(SKADNETWORK_FILE):
		for line in FileAccess.get_file_as_string(SKADNETWORK_FILE).split("\n"):
			var identifier := line.strip_edges()
			if identifier.is_empty() or identifier.begins_with("#"):
				continue
			identifiers.append(identifier)
	if identifiers.is_empty():
		identifiers = PackedStringArray(DEFAULT_SKADNETWORK_IDS)
		if str(_config.ads["provider"]) == "applovin_max":
			push_warning(
				"[MobileServices] no %s, so only Google's SKAdNetwork " % SKADNETWORK_FILE
				+ "identifier is declared. A MAX waterfall needs every mediated "
				+ "network's identifier or their installs go unattributed — "
				+ "see docs/ios.md."
			)
	return identifiers


## Puts GoogleService-Info.plist next to the executable, which is where the
## Firebase iOS SDK looks for it.
func _bundle_firebase_plist() -> void:
	if not _modules.has("firebase"):
		return
	for path in FIREBASE_PLIST_PATHS:
		if FileAccess.file_exists(path):
			add_ios_bundle_file(path)
			print("[MobileServices] bundled %s" % path)
			return
	push_error(
		"[MobileServices] analytics are enabled but no GoogleService-Info.plist was "
		+ "found at %s. " % " or ".join(FIREBASE_PLIST_PATHS)
		+ "Firebase cannot start without it and the build will report nothing."
	)


## The Podfile lines this configuration implies, printed into the export log.
##
## The SDK cannot install them: Godot generates the Xcode project, and CocoaPods
## is a step somebody runs afterwards. What it can do is say exactly which pods
## the modules it just enabled expect to find — which is the part people get
## wrong, because a missing pod is a link error a long way from its cause.
func _podfile_advice() -> String:
	var pods := PackedStringArray()
	if _modules.has("firebase"):
		pods.append("  pod 'FirebaseAnalytics'")
		if bool(_config.analytics["crashlytics_enabled"]):
			pods.append("  pod 'FirebaseCrashlytics'")
		if bool(_config.analytics["remote_config_enabled"]):
			pods.append("  pod 'FirebaseRemoteConfig'")
	if _modules.has("ads"):
		pods.append("  pod 'Google-Mobile-Ads-SDK'")
	if _modules.has("consent"):
		pods.append("  pod 'GoogleUserMessagingPlatform'")
	for extra in _config.ads["extra_ios_pods"]:
		var line := str(extra).strip_edges()
		if not line.is_empty():
			pods.append("  pod %s" % line if line.begins_with("'") else "  pod '%s'" % line)
	if pods.is_empty():
		# StoreKit and GameKit are part of iOS, so a build with only those needs
		# nothing at all — worth saying, rather than printing an empty list.
		return "[MobileServices] no CocoaPods dependencies are needed for this configuration."
	return (
		"[MobileServices] this configuration needs the following in the generated\n"
		+ "  Xcode project's Podfile (see docs/ios.md):\n"
		+ "\n".join(pods)
	)


static func _escape(value: String) -> String:
	return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
